---
branch: main
# check:
# - CKV_DOCKER_1
compact: true
# directory:
# - test-dir
# docker-image: TODO
dockerfile-path: Dockerfile
download-external-modules: true
evaluate-variables: true
# external-checks-dir:
# - sample-dir
external-modules-download-path: .external_modules
framework:
  - all
# skip-download: true
# quiet: true
# repo-id: TODO
# skip-check:
# - CKV_DOCKER_3
# - CKV_DOCKER_2
# skip-framework:
# - dockerfile
# - secrets
soft-fail: true
