# vi: ft=yaml.ansible.jinja2
---
fail_fast: true
minimum_pre_commit_version: 2.20.0
exclude: "docs/_build/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-ast
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=123']
        exclude: >
          (?x)^(
            .pnp.cjs|
            package-lock.json|
            npm-shrinkwrap.json|
            poetry.lock|
            Pipfile.lock|
            yarn.lock|
          )$
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
        exclude: >
          (?x)^(
              clean.bat|
              build.bat|
              mvnw.cmd|
              .mvn/|
              .venv|
              .direnv|
          )$
      - id: check-json
        exclude: >
          (?x)^(
            .vscode/|
          )$
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: >
          (?x)^(
            .gitlab-ci.yml|
            k8s/.*|
          )$
      - id: check-symlinks
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^.cache/
      - id: detect-private-key
        exclude: >
          (?x)^(
              README.md|
              .ssh/id_rsa|
              roles/jenkins-master/defaults/main.yml|
              roles/jenkins-master/README.md|
          )$
      # Disable as incompatible with black formatting
      # - id: double-quote-string-fixer
      #   exclude: >
      #     (?x)^(
      #         tests/.*|
      #     )$
      - id: name-tests-test
        exclude: >
          (?x)^(
              tests/.*|
          )$
#      - id: no-commit-to-branch
#        args: [--branch, main, --branch, master, --branch, release/*]
      - id: end-of-file-fixer
#      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: file-contents-sorter
  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v4.2.0
    hooks:
      - id: validate_manifest
#  - repo: https://github.com/asottile/reorder_python_imports.git
#    rev: v3.8.5
#    hooks:
#      - id: reorder-python-imports
#        exclude: ^.cache/
#  #    language_version: python3
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v2.3.0
  #   hooks:
  #     - id: add-trailing-comma
  # - repo: https://github.com/willthames/ansible-lint.git
  #   rev: v24.6.0
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
  #       exclude: >
  #         (?x)^(
  #           .travis.yml|
  #           .gitlab-ci.yml|
  #         )$
  - repo: https://github.com/doublify/pre-commit-hindent.git
    rev: b3680b6ebf9f7cf29b19307f246adef66756feef
    hooks:
      - id: hindent
  # - repo: https://github.com/scop/pre-commit-shfmt
  #   rev: v3.10.0-2
  #   hooks:
  #     - id: shfmt-docker  # Docker image (requires Docker to run)
  #       exclude: >
  #         (?x)^(
  #           .git-prompt.sh|
  #         )$
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [-x]
        exclude: >
          (?x)^(
            mvnw|
            hooks|
            tests/.*|
          )$
  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v1.0.1
    hooks:
      - id: encryption-check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        args: [--maxdepth, "3", -i]
      # - id: dockerfile_lint
      #   args: [--permissive, --verbose, --dockerfile, ./Dockerfile]
      #   always_run: false
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks-docker
        entry: zricethezav/gitleaks protect --verbose --redact --staged
  - repo: https://github.com/oxsecurity/megalinter
    rev: v8.8.0
    hooks:
      - id: megalinter-incremental  # Faster, less thorough
        stages:
          - pre-commit
        args:
          - mega-linter-runner
          - --containername
          - "megalinter-incremental"
          - --remove-container
          # - --fix
          # - --env
          # - "'APPLY_FIXES=all'"
          - --env
          - "'CLEAR_REPORT_FOLDER=true'"
          - --env
          - "'LOG_LEVEL=warning'"
          - --filesonly
          - --flavor
          - "ci_light"
  # - repo: local
  #   hooks:
  #     - id: lint
  #       name: Lint
  #       entry: python3 -m nox -rs lint
  #       language: system
  #       pass_filenames: false
  #     - id: black
  #       name: Black
  #       entry: python3 -m nox -rs black
  #       language: system
  #       pass_filenames: false
  #     - id: test
  #       name: Test
  #       entry: python3 -m nox -rs test
  #       language: system
  #       pass_filenames: false
